product/urls.py
from django.urls import path, re_path
from product import views

urlpatterns = [
    
    path('category/create/', views.create_category, name='create_category'),
    path("", views.categories, name="categories"),
    re_path(r'^category/edit/(?P<pk>.*)/$', views.edit_category, name='edit_category'),
    re_path(r'^delete-category/(?P<pk>.*)/$', views.delete_category, name='delete_category'),    
    re_path(r'^category/(?P<pk>.*)/$', views.category, name='category')    
    
]

product_management/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include(('product.urls','product'),namespace='product'))
]

main/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Category(models.Model):
    name = models.CharField(max_length=128)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['name']


    def __str__(self):
        return str(self.name)

class Product(models.Model):
    name = models.CharField(max_length=60)
    price = models.IntegerField(default=0)
    category = models.ForeignKey("product.Category", on_delete=models.CASCADE, limit_choices_to={'is_deleted': False})
    description = models.TextField()
    image = models.ImageField(upload_to="uploads/products/")
    is_deleted = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = ['name']

    def __str__(self):
        return str(self.name)

product/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea, HiddenInput, Select
from django.utils.translation import gettext_lazy as _
from product.models import Category, Product


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ['is_deleted']
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control ', 'placeholder': 'Name'})
        }
        error_messages = {
            'name': {
                'required': _("Name field is required."),
            }
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['is_deleted']
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control ', 'placeholder': 'Name'}),
            'price': TextInput(attrs={'class': 'required form-control ', 'placeholder': 'Price'}),
            'category': Select(attrs={'class': 'required form-control ', 'placeholder': 'Category'}),
            'description': TextInput(attrs={'class': 'required form-control ', 'placeholder': 'Description'})
        }
        error_messages = {
            'name': {
                'required': _("Name field is required."),
            },
            'price': {
                'required': _("Price field is required."),
            },
            'category': {
                'required': _("Category field is required."),
            },
            'description': {
                'required': _("Description field is required."),
            },
        }

main/views.py
from django.shortcuts import render

# Create your views here.

product/views.py
import datetime
import json

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.db.models import Q
from django.http.response import HttpResponse

from main.functions import generate_form_errors
from product.forms import CategoryForm
from product.forms import ProductForm
from product.models import Category, Product




# category crud starts here
def create_category(request):
    
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            if not Category.objects.filter(name=name,is_deleted=False).exists():
                Category(                    
                    name = name
                ).save()
                response_data = {
                    "status": "true",
                    "title": "Successfully Created",
                    "message": "Category created successfully.",
                    "redirect": "true",
                    "redirect_url": reverse('product:categories')
                }
            else:    
                response_data = {
                    "status": "false",
                    "stable": "true",
                    "title": "This category already exists",
                    "message": "Category already exists",                        
                }
        else:
            message = generate_form_errors(form, formset=False)
            
            response_data = {
                "stable": "true",
                "status": "form_error",
                "title": "Form validation error",
                "message": str(message),               
            }
        return HttpResponse(json.dumps(response_data), content_type='application/json')
    else:
        form = CategoryForm()
        context = {
            "title": "Create Category",
            "form": form,
            "redirect": "true",
            "create":True
        }
        return render(request, 'category/create_category.html', context)

def categories(request):
    instances = Category.objects.filter(is_deleted=False)
    paginator = Paginator(instances,1000000000000)
    page_number = request.GET.get('page')
    instances = paginator.get_page(page_number)
    context = {
        'instances': instances,
        "title": 'Categories',
    }
    return render(request, "category/categories.html", context)


def edit_category(request, pk):
    instance = get_object_or_404(Category.objects.filter(pk=pk, is_deleted=False))
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=instance)

        if form.is_valid():
            data = form.save(commit=False)
            data.updator = request.user
            data.date_updated = datetime.datetime.now()
            data.save()

            response_data = {
                "status": "true",
                "redirect" : "true",
                "title": "Successfully Updated",
                "message": "Category updated successfully.",                
                "redirect_url": reverse('product:categories')
            }

        else:
            message = generate_form_errors(form, formset=False)
            response_data = {
                "stable": "true",
                "status": "form_error",
                "message": str(message),
                "title": "Form validation error"  
            }
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = CategoryForm(instance=instance)
        context = {
            "form": form,
            "instance": instance,
            "title": "Edit Category :" + instance.name,
            "redirect": "true",
            "url": reverse('product:edit_category', kwargs={'pk': instance.pk})
        }
        return render(request, 'category/create_category.html', context)
    

def category(request, pk):
    instance = get_object_or_404(Category.objects.filter(pk=pk,is_deleted=False))
    context = {
        'instance': instance,
        'title': 'Category'
    }
    return render(request, "category/category.html", context)


def delete_category(request,pk):
    instance = get_object_or_404(Category.objects.filter(pk=pk,is_deleted=False))
    Category.objects.filter(pk=pk).update(is_deleted=True,name=instance.name)
    response_data = {
        "status" : "true",        
        "title" : "Successfully Deleted",
        "message" : "Category Successfully Deleted.", 
        "redirect" : "true",       
        "redirect_url" : reverse('product:categories')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load static %}
    <title>Admin  - Dashboard</title>
    <!-- Favicon -->
    <link href="{% static 'job_portal/img/logo1.png'%}" rel="icon">


    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/material-design-iconic-font.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/material-design-iconic-font.css' %}" rel="stylesheet">
    
</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <!-- <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div> -->
                <div class="sidebar-brand-text mx-3"> <sup>Admin</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            
            <li class="nav-item">
                
                <a class="nav-link collapsed" href="{% url 'product:categories' %}" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>CATEGORIES</span>
                </a>    
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'product:create_category' %}"  data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>CATEGORY CREATION</span>
                </a>
            </li>
            <!-- Nav Item - Utilities Collapse Menu -->
           
            <!-- Divider -->
            <hr class="sidebar-divider">
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                   

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        </li>
                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Admin</span>
                                <img class="img-profile rounded-circle"
                                    src="{% static 'img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                {% comment %} <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a> {% endcomment %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->

                {% block content %}

                {% endblock %}
            
            </div>
            <!-- End of Main Content -->           
    
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Amina K M </span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-bar-demo.js' %}"></script>

</body>

</html>

templates/category/categories.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex">
                <h6 class="m-0 font-weight-bold text-primary">HRMS Clients</h6>
                 <!-- Topbar Search -->
                 <form class="d-none d-sm-inline-block form-inline mr-auto md-3 my-2 my-md-0 mw-100 navbar-search" style="margin-left: 70%;">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control bg-light border-0 small" placeholder="Search for..."
                            aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" style="width:100%">
                        <thead>
                            <tr>
                                <th style="width:5%">Sl. No.</th>
                                <th style="width:15%">Category Name</th>
                                <th style="width:15%">Actions</th>
                            </tr>
                        </thead>                        
                        <tbody>
                            {% for instance in instances %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{instance.name}}</td>
                                
                                <td>                                    
                                    <a href="{% url 'product:category' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"title="View category"><i class="zmdi zmdi-eye" ></i></a>                                    
                                    <a href="{% url 'product:edit_category' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"title="Edit category" ><i class="zmdi zmdi-edit"></i></a>                                    
                                    <a data-id="{{instance.pk}}" href="{% url 'product:delete_category' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>     
                                </td>                                
                            </tr>
                            {% endfor %}                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>  

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        // Function to handle delete action
        function handleDelete(pk) {
            Swal.fire({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this HRMS Client!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            })
            .then((result) => {
                if (result.isConfirmed) {
                    // If user confirms, send Fetch API request to delete
                    fetch('{% url "product:delete_category" pk=0 %}'.replace('0', pk), {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                    })
                    .then(response => response.json())
                    .then(data => {
                        // Handle success response
                        if (data.status === "true") {
                            Swal.fire({
                                title: data.title,
                                text: data.message,
                                icon: "success",
                            })
                            .then((value) => {
                                // Redirect to the specified URL after success
                                window.location.href = data.redirect_url;
                            });
                        } else {
                            Swal.fire("Error", "An error occurred while deleting.", "error");
                        }
                    })
                    .catch(() => {
                        // Handle error
                        Swal.fire("Error", "An error occurred while processing the request.", "error");
                    });
                } else {
                    Swal.fire("HRMS Client is safe!");
                }
            });
        }
    
        // Attach click event to delete button
        document.querySelectorAll('.remove').forEach(function(el) {
            el.addEventListener('click', function(e) {
                e.preventDefault();
                var pk = this.getAttribute('data-id');
                handleDelete(pk);
            });
        });
    </script>
    
 
   
    <!-- /.container-fluid -->
{% endblock %}

templates/category/category.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Section: Design Block -->
<section class="" style="width: 70%;margin-top: -3%;margin-left: 25%;">    
    <div class="px-4 py-5 px-md-5 text-center text-lg-start" >
      <div class="container">
        <div class="row gx-lg-5 align-items-center">            
          <div class="col-lg-8 mb-5 mb-lg-0">           
            <div class="card">
              <h3 style="margin-top: 3%;color: #2c9792;">Category Details</h3>
              <div class="card-body py-5 px-md-5">
                      <div class="form-outline mb-4">  
                        <label class="form-label" for="form3Example1" style="color: black; font-weight: bolder;">Category name</label> 
                        {{ instance.name }}  
                      </div>
                      
                                   
              </div>
            </div>            
          </div>
        </div>
      </div>
    </div>
  </section>

 
{% endblock %}

templates/category/create_category.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Section: Design Block -->
<section class="" style="width: 70%;margin-top: -3%;margin-left: 25%;">
    
    <div class="px-4 py-5 px-md-5 text-center text-lg-start" >
      <div class="container">
        <div class="row gx-lg-5 align-items-center">
            
          <div class="col-lg-8 mb-5 mb-lg-0">
            {% if create %}
            <div class="card">
              <h3 style="margin-top: 3%;color: #2c9792;">Category Creation Form</h3>
              <div class="card-body py-5 px-md-5">
                <form id="categoryform" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <!-- 2 column grid layout with text inputs for the first and last names -->
                  <div class="row" style="margin-top: -5%;">
                    <div class="col-md-12 mb-4">
                      <div class="form-outline">
                        {{ form.name }}
                        {% if form.name.errors %}
                          <span class="error">{{ form.name.errors.0 }}</span>
                        {% endif %}
                        <label class="form-label">Category name</label>
                      </div>
                    </div>
                    
                  </div>
  
                  
                  <!-- Submit button -->
                  <button type="submit" class="btn btn-primary btn-block mb-4" onclick="submitForm(event)">
                    Create Category
                  </button> 
                  
                </form>
              </div>
            </div>
            {% else %}
            <div class="card">
              <h3 style="margin-top: 3%;color: #2c9792;">Update Category Form</h3>
              <div class="card-body py-5 px-md-5">
                <form id="categoryform" method="post" enctype="multipart/form-data" class="ajax">
                  {% csrf_token %}

                  <!-- 2 column grid layout with text inputs for the first and last names -->
                  <div class="row" style="margin-top: -5%;">
                    <div class="col-md-12 mb-12">
                      <div class="form-outline">
                        {{ form.name }}
                        {% if form.name.errors %}
                          <span class="error">{{ form.name.errors.0 }}</span>
                        {% endif %}
                        <label class="form-label">Category name</label>
                      </div>
                    </div>
                    
                  </div>
  
                  
                  <!-- Submit button -->
                  <button type="submit" class="btn btn-primary btn-block mb-4" onclick="submitForm(event)">
                    Update Category
                  </button> 
                  
                </form>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Include SweetAlert JS from CDN -->
  
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

 
<!-- Add JavaScript code to handle form submission and show SweetAlert messages -->
<script>
  function submitForm(event) {
    event.preventDefault();  // Prevent the default form submission behavior
    var form = document.getElementById('categoryform');
    var formData = new FormData(form);
  
    fetch(form.action, {
      method: 'POST',
      body: formData,
    })
    .then(response => response.json())
    .then(data => {
      console.log(data);
      console.log("status", data.status);
      console.log('data.redirect_url:', data.redirect_url);
  
      // Corrected variable name here
      if (data.status === 'true') {
        console.log("status is true");
        console.log("redirect url", data.redirect_url);
        showSweetAlert(data.message, data.status, data.redirect_url);
      } else if (data.status === 'form_error') {
        console.log("status is form_error");
        showSweetAlert(data.message, 'form_error');
      } else if (data.status === 'false') {
        console.log("status is false");
        showSweetAlert(data.message, data.status);
      } else {
        console.log("status is neither true or false");
        showSweetAlert(data.message, 'error');
      }
    })
    .catch(error => {
      console.error('Error:', error);
    });
  }
  
  function showSweetAlert(message, status, redirectUrl) {
    console.log('showSweetAlert called');
    console.log('message:', message);
    console.log('status:', status);
    console.log('redirectUrl:', redirectUrl);
  
    if (status === 'true') {
      Swal.fire({
        icon: 'success',
        title: 'Success!',
        text: message,
        showConfirmButton: true,
        allowOutsideClick: false, // Prevent closing on outside click
  
        didClose: () => {
          console.log('Redirecting to:', redirectUrl);
          if (redirectUrl) {
            // Combine the redirect URL with the current protocol and host to get the full URL
            var fullRedirectUrl = window.location.origin + redirectUrl;
            console.log('Full Redirect URL:', fullRedirectUrl);
            window.location.href = fullRedirectUrl;
          }
        }
      });
    } else if (status === 'form_error') {
      console.log('Showing form error alert');
      Swal.fire({
        icon: 'error',
        title: 'Form Validation Error!',
        html: message,  // Display form errors as HTML
        showConfirmButton: true,
        allowOutsideClick: false,
      });
    } else if (status === 'false') {
      console.log('Showing form error alert');
      Swal.fire({
        icon: 'error',
        title: 'Form Error!',
        text: 'Error: ' + message,
        showConfirmButton: true,
        allowOutsideClick: false, // Prevent closing on outside click
      });
    } else {
      console.log('Showing error alert');
      Swal.fire({
        icon: 'error',
        title: 'Error!',
        text: 'Error: ' + message,
        showConfirmButton: true,
        allowOutsideClick: false, // Prevent closing on outside click
      });
    }
  }
  
</script>

{% endblock %}